PET_PLACES: |
  - Table name: PET_PLACES
  - Description: This table contains detailed information about pet-friendly facilities, including their location, amenities, and rules for pet accommodation.
  - Columns:
      - FACILITY_NM (TEXT): Name of the facility.
      - CATEGORY_NM (TEXT): Category name of the facility. (동물병원, 동물약국, 문예회관, 미술관, 미용, 박물관, 반려동물용품, 식당, 여행지, 위탁관리, 카페, 펜션, 호텔)
      - CTPRVN_NM (TEXT): Name of the province or metropolitan city where the facility is located. (경기도, 전라남도, 서울특별시, 인천광역시, 경상북도, 대구광역시, 세종특별자치시, 전라북도, 경상남도, 강원도, 부산광역시, 광주광역시, 대전광역시, 충청북도, 제주특별자치도, 충청남도, 울산광역시)
      - SIGNGU_NM (TEXT): Name of the district (시/군/구) where the facility is located.
      - LEGALDONG_NM (TEXT): Name of the legal district (동/면/읍).
      - LI_NM (TEXT): Name of the administrative subdivision (리).
      - ROAD_NAME_ADDRESS (TEXT): Road name address of the facility.
      - LAND_LOT_ADDRESS (TEXT): Land-lot number address of the facility.
      - TEL_NO (TEXT): Contact phone number of the facility.
      - HOMEPAGE_URL (TEXT): Website URL of the facility.
      - HOLIDAY_INFORMATION (TEXT): Information about facility closure days.
      - OPEN_HOUR_MON (TEXT): Opening hours of the facility on Monday (format: hh:mm)
      - CLOSE_HOUR_MON (TEXT): Closing hours of the facility on Monday (format: hh:mm)
      - OPEN_HOUR_TUE (TEXT): Opening hours of the facility on Tuesday (format: hh:mm)
      - CLOSE_HOUR_TUE (TEXT): Closing hours of the facility on Tuesday (format: hh:mm)
      - OPEN_HOUR_WED (TEXT): Opening hours of the facility on Wednesday (format: hh:mm)
      - CLOSE_HOUR_WED (TEXT): Closing hours of the facility on Wednesday (format: hh:mm)
      - OPEN_HOUR_THU (TEXT): Opening hours of the facility on Thursday (format: hh:mm)
      - CLOSE_HOUR_THU (TEXT): Closing hours of the facility on Thursday (format: hh:mm)
      - OPEN_HOUR_FRI (TEXT): Opening hours of the facility on Friday (format: hh:mm)
      - CLOSE_HOUR_FRI (TEXT): Closing hours of the facility on Friday (format: hh:mm)
      - OPEN_HOUR_SAT (TEXT): Opening hours of the facility on Saturday (format: hh:mm)
      - CLOSE_HOUR_SAT (TEXT): Closing hours of the facility on Saturday (format: hh:mm)
      - OPEN_HOUR_SUN (TEXT): Opening hours of the facility on Sunday (format: hh:mm)
      - CLOSE_HOUR_SUN (TEXT): Closing hours of the facility on Sunday (format: hh:mm)
      - OPENING_WEEKDAYS (TEXT): Operating weekdays of the facility (e.g. 월화금토일)
      - OPERATION_TIME_DISPLAY (TEXT): Operating hours of the facility for display. Do not use this column in sql filtering.
      - PARKING_LOT_YN (TEXT): Indicates whether parking is available (Y/N).
      - USAGE_PRICE (TEXT): Details about usage fees. Do not use this column in sql filtering.
      - POSIBLE_PET_SIZE (TEXT): Size limits for pets allowed entry. Do not use this column in sql filtering.
      - PET_LIMIT (TEXT): Restrictions or rules for pet accommodation. Do not use this column in sql filtering.
      - PET_POSSIBLE_AT_INDOOR (TEXT): Indicates whether pets are allowed indoors (Y/N). Do not use this column in sql filtering.
      - PET_POSSIBLE_AT_OUTDOOR (TEXT): Indicates whether pets are allowed outdoors (Y/N). Do not use this column in sql filtering.
      - FACILITY_INFORMATION (TEXT): Detailed description of the facility. Do not use this column in sql filtering.
      - ADDITIONAL_CHARGE_ON_PET (TEXT): Additional charges for pet accommodation. Do not use this column in sql filtering.
      - SUMMARY (TEXT): Description or reviews of the facility Do not use this column in sql filtering.

CHILDREN_PLACES: |
  - Table name: CHILDREN_PLACES
  - Description: This is the location data of cultural facilities that can be accompanied by family children such as age of entry, parking, nursing room, stroller rental, and kids zone.
  - Columns:
      - FCLTY_NM (TEXT): Name of the facility.
      - MRHST_NM (TEXT): Name of the franchise or affiliated business managing the facility.
      - CTGRY_ONE_NM (TEXT): First-level category of the facility ('전시/공연', '문화관광/명소').
      - CTGRY_TWO_NM (TEXT): Second-level category of the facility ('영화/연극/공연', '전시/기념관', '관광지', '명승지').
      - CTGRY_THREE_NM (TEXT): Third-level category of the facility, if applicable. ('N', '기타전시/박물관', '공연/연극/문화센터', '미술관', '대형기념관/묘역', '테마공원/대형놀이공원', '유명관광지', '아쿠아리움/대형수족관', '해수욕장', '대형예술센터', '일반유원지/일반놀이공원', '휴양림/수목원', '성/성터', '식물원', '대형전시/박물관', '궁궐/종묘', '동물원', '컨벤션센터', '대형미술관', '도서관', '글램핑코리아(캠핑)', '일반유원지')
      - CTPRVN_NM (TEXT): Name of the province or metropolitan city where the facility is located.
      - SIGNGU_NM (TEXT): Name of the district (시군구) where the facility is located.
      - LEGALDONG_NM (TEXT): Name of the legal district (동/면/읍) where the facility is located.
      - LI_NM (TEXT): Name of the administrative subdivision (리), if applicable.
      - LNBR_NO (TEXT): Land lot number of the facility.
      - ROAD_NM (TEXT): Road name where the facility is located.
      - BULD_NO (TEXT): Building number of the facility.
      - LC_LA (TEXT): Latitude of the facility location.
      - LC_LO (TEXT): Longitude of the facility location.
      - ZIP_NO (TEXT): Postal code of the facility location.
      - RDNMADR_NM (TEXT): Road name address of the facility.
      - LNM_ADDR (TEXT): Land-lot number address of the facility.
      - TEL_NO (TEXT): Contact phone number of the facility.
      - HMPG_URL (TEXT): Official website URL of the facility.
      - BLOG_URL (TEXT): Blog URL with additional information about the facility.
      - FACEBOOK_URL (TEXT): Facebook page URL of the facility.
      - INSTGRM_URL (TEXT): Instagram page URL of the facility.
      - RSTDE_GUID_CN (TEXT): Information about closure days (e.g., holidays or maintenance).
      - OPER_TIME (TEXT): Operating hours of the facility.
      - FRE_PARKNG_AT (TEXT): Indicates whether free parking is available (Y/N).
      - CHGD_PARKNG_AT (TEXT): Indicates whether paid parking is available (Y/N).
      - ENTRN_PRICE_AT (TEXT): Indicates whether there is an entrance fee (Y/N).
      - ENTRN_POSBL_BN_VALUE (TEXT): Entry age or restrictions (e.g., 연령제한없음).
      - DSPSN_TOILET_AT (TEXT): Indicates whether there is a designated restroom for persons with disabilities (Y/N).
      - NRSGRM_AT (TEXT): Indicates whether a nursing room is available (Y/N).
      - STROLLER_LEND_AT (TEXT): Indicates whether stroller rental is available (Y/N).
      - KIDS_ZONE_AT (TEXT): Indicates whether there is a designated kids' zone (Y/N).
