PET_PLACES:
  - INDEX
  - FACILITY_NM
  - ROAD_NAME_ADDRESS
  - LAND_LOT_ADDRESS
  - TEL_NO
  - HOMEPAGE_URL
  - HOLIDAY_INFORMATION
  - OPERATION_TIME_DISPLAY
  - PARKING_LOT_YN
  - USAGE_PRICE
  - POSIBLE_PET_SIZE
  - PET_LIMIT
  - PET_POSSIBLE_AT_INDOOR
  - PET_POSSIBLE_AT_OUTDOOR
  - FACILITY_INFORMATION
  - ADDITIONAL_CHARGE_ON_PET
  - SUMMARY